version: '3'
services:
    #Postgres
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_USERNAME=postgres
            - POSTGRES_DB=simple_blog_api
    #simple-blog-api
    simple-blog-api:
        depends_on:
            - postgres
        image: saikrishnakasula/simple_blog_api
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
          - "3000:3000"
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_USERNAME=postgres
            - POSTGRES_DB=simple_blog_api